### ISSUE TITLE
Joins where many tables can satisfy a column are incorrect

### ISSUE THREAD

**Issue by vqtran** [vqtran/EchoQuery#20]
Just an example so we don't forget:

"how many orders are there where name is Sally"

Is correct because our joining defaults to the first (or is it last?) matching table, in this case it's the customers table.

"how many orders are there where name is "ivory azure"
There are zero rows in the orders table where the value in the name column is equal to ivory azure.

When there's actually 38. This query still tries to join with name. Here's what we need to do:

1. Attach table names to each QueryRequest by default, and expose utterances where the user can specify the table name. A concern here is that this might blow up utterances even more.

2. SchemaInferrer now doesn't return a JoinRecipe with the getXPrefix() methods, but fills in the table name fields in the QueryRequest object with inferred values. Better software engineering anyways!

3. If SchemaInferrer has many options and it can't decide, we need to prompt the user to clarify which one. This is a good introduction to interactive features for us.

**Comment by GabeLoins** [comment]
omg our first issue

**Comment by vqtran** [comment]
Trapped in a closet
