### ISSUE TITLE
Add GET option to Query Intent (TIED CLOSELY WITH HANDLING TABLES INTERNALLY)

### ISSUE THREAD

**Issue by GabeLoins** [vqtran/EchoQuery#33]
>In the current version of EchoQuery, basic query request can only contain one result column [...] to add > or remove additional result columns, the Refine Intent has to be used. 

> Get the {Column}(s) of {Table}(s)?

to do this, we would need to create another entry in the AGGREGATE slot that is like "Get/Retrieve/Obtain/Print" and then handle getting internally. this is important to do earlier!!

**Comment by vqtran** [comment]
I actually was part way through implementing this a month ago! I have a branch with huge changes that I'll have to refigure out what I was doing

**Comment by vqtran** [comment]
This works for SELECT *, maybe we don't need it for a single column? Deprioritizing.
