### ISSUE TITLE
Clarify Intent, Store Default Tables for Columns

### ISSUE THREAD

**Issue by GabeLoins** [vqtran/EchoQuery#41]
In the situation "...where name is Sally"

"did you mean Customer Name or Part Name?"

"Customer Name",

our service should save (per session, per user, per db?) what the default is and then use it

Should we allow overwriting?

**Comment by vqtran** [comment]
I think this isn't a good feature because ambiguity resolution doesn't always mean that there's a default all the time. For example, for "how many orders where name is sally" the name column shouldn't always default to customer name. I think we'll have to invent a more clever way of doing this

**Comment by GabeLoins** [comment]
yeah I see where you're coming from here.

Maybe we should do something like spelling correction? Like if they ask for a table that we dont recognize (sales instead of orders), we can save that sales ==> orders

**Comment by GabeLoins** [comment]
We talked about that with them before not sure why they went for the join inference over spelling correction.

**Comment by vqtran** [comment]
Closing, bad idea.
